### ISSUE TITLE
Add jetske and Oline

### ISSUE THREAD

**Issue by rem0g** [sign-language-processing/lexicon-induction#2]
We want to add Jetske Adams https://github.com/Jetske  and Oline https://github.com/OlineRanum here.

@AmitMY you have admin access, can you do that and also make me admin?

Danke Schon!

**Comment by AmitMY** [comment]
All three of you were now invited (check email), with write access.

Please note: the `main` branch is protected. 
When working on whatever feature, work in a branch, and make a pull request.
Make the smallest change possible (ideally, each branch is one feature), and then branch from there to do something else, so every feature can be reviewed separately.
